# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

workflows:
  version: 2
  test-publish:
    jobs:
      - publish:
          context: npm_publish
          filters:
            branches:
              only: master


defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: node:alpine
  environment:
    NODE_ENV: test

jobs:
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/tmp/.npmrc
      - run:
          name: Publish package
          command: npm publish 
